[package]
name = "opendex-sc-sft-nft-staking-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.opendex-sc-sft-nft-staking]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.63.3"
default-features = false
